package entidades;
// Generated 18/07/2019 10:48:46 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private Integer codigoCliente;
     private Persona persona;
     private Date fechaNac;
     private String direccion;
     private Set reservarcitas = new HashSet(0);
     private Set mascotaporclientes = new HashSet(0);

    public Cliente() {
    }

	
    public Cliente(Persona persona, Date fechaNac) {
        this.persona = persona;
        this.fechaNac = fechaNac;
    }
    public Cliente(Persona persona, Date fechaNac, String direccion, Set reservarcitas, Set mascotaporclientes) {
       this.persona = persona;
       this.fechaNac = fechaNac;
       this.direccion = direccion;
       this.reservarcitas = reservarcitas;
       this.mascotaporclientes = mascotaporclientes;
    }
   
    public Integer getCodigoCliente() {
        return this.codigoCliente;
    }
    
    public void setCodigoCliente(Integer codigoCliente) {
        this.codigoCliente = codigoCliente;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public Date getFechaNac() {
        return this.fechaNac;
    }
    
    public void setFechaNac(Date fechaNac) {
        this.fechaNac = fechaNac;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public Set getReservarcitas() {
        return this.reservarcitas;
    }
    
    public void setReservarcitas(Set reservarcitas) {
        this.reservarcitas = reservarcitas;
    }
    public Set getMascotaporclientes() {
        return this.mascotaporclientes;
    }
    
    public void setMascotaporclientes(Set mascotaporclientes) {
        this.mascotaporclientes = mascotaporclientes;
    }




}


