package entidades;
// Generated 18/07/2019 10:48:46 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Mascota generated by hbm2java
 */
public class Mascota  implements java.io.Serializable {


     private Integer idMascota;
     private String nombreMascota;
     private String colorMascota;
     private String raza;
     private Set mascotaporclientes = new HashSet(0);

    public Mascota() {
    }

	
    public Mascota(String nombreMascota, String colorMascota, String raza) {
        this.nombreMascota = nombreMascota;
        this.colorMascota = colorMascota;
        this.raza = raza;
    }
    public Mascota(String nombreMascota, String colorMascota, String raza, Set mascotaporclientes) {
       this.nombreMascota = nombreMascota;
       this.colorMascota = colorMascota;
       this.raza = raza;
       this.mascotaporclientes = mascotaporclientes;
    }
   
    public Integer getIdMascota() {
        return this.idMascota;
    }
    
    public void setIdMascota(Integer idMascota) {
        this.idMascota = idMascota;
    }
    public String getNombreMascota() {
        return this.nombreMascota;
    }
    
    public void setNombreMascota(String nombreMascota) {
        this.nombreMascota = nombreMascota;
    }
    public String getColorMascota() {
        return this.colorMascota;
    }
    
    public void setColorMascota(String colorMascota) {
        this.colorMascota = colorMascota;
    }
    public String getRaza() {
        return this.raza;
    }
    
    public void setRaza(String raza) {
        this.raza = raza;
    }
    public Set getMascotaporclientes() {
        return this.mascotaporclientes;
    }
    
    public void setMascotaporclientes(Set mascotaporclientes) {
        this.mascotaporclientes = mascotaporclientes;
    }




}


