package entidades;
// Generated 18/07/2019 10:48:46 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Personal generated by hbm2java
 */
public class Personal  implements java.io.Serializable {


     private Integer idpersonal;
     private Persona persona;
     private String dni;
     private String cargo;
     private Set atencions = new HashSet(0);
     private Set reservarcitas = new HashSet(0);

    public Personal() {
    }

	
    public Personal(Persona persona, String dni) {
        this.persona = persona;
        this.dni = dni;
    }
    public Personal(Persona persona, String dni, String cargo, Set atencions, Set reservarcitas) {
       this.persona = persona;
       this.dni = dni;
       this.cargo = cargo;
       this.atencions = atencions;
       this.reservarcitas = reservarcitas;
    }
   
    public Integer getIdpersonal() {
        return this.idpersonal;
    }
    
    public void setIdpersonal(Integer idpersonal) {
        this.idpersonal = idpersonal;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }
    public String getCargo() {
        return this.cargo;
    }
    
    public void setCargo(String cargo) {
        this.cargo = cargo;
    }
    public Set getAtencions() {
        return this.atencions;
    }
    
    public void setAtencions(Set atencions) {
        this.atencions = atencions;
    }
    public Set getReservarcitas() {
        return this.reservarcitas;
    }
    
    public void setReservarcitas(Set reservarcitas) {
        this.reservarcitas = reservarcitas;
    }




}


