package entidades;
// Generated 18/07/2019 10:48:46 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Tipoatencion generated by hbm2java
 */
public class Tipoatencion  implements java.io.Serializable {


     private Integer idtipoatencion;
     private String descripcion;
     private Set atencions = new HashSet(0);

    public Tipoatencion() {
    }

	
    public Tipoatencion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Tipoatencion(String descripcion, Set atencions) {
       this.descripcion = descripcion;
       this.atencions = atencions;
    }
   
    public Integer getIdtipoatencion() {
        return this.idtipoatencion;
    }
    
    public void setIdtipoatencion(Integer idtipoatencion) {
        this.idtipoatencion = idtipoatencion;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getAtencions() {
        return this.atencions;
    }
    
    public void setAtencions(Set atencions) {
        this.atencions = atencions;
    }




}


