package entidades;
// Generated 18/07/2019 10:48:46 PM by Hibernate Tools 4.3.1



/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private Integer idusuario;
     private Persona persona;
     private String usuario;
     private String password;
     private String perfil;
     private Character estado;

    public Usuario() {
    }

	
    public Usuario(Persona persona) {
        this.persona = persona;
    }
    public Usuario(Persona persona, String usuario, String password, String perfil, Character estado) {
       this.persona = persona;
       this.usuario = usuario;
       this.password = password;
       this.perfil = perfil;
       this.estado = estado;
    }
   
    public Integer getIdusuario() {
        return this.idusuario;
    }
    
    public void setIdusuario(Integer idusuario) {
        this.idusuario = idusuario;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getPerfil() {
        return this.perfil;
    }
    
    public void setPerfil(String perfil) {
        this.perfil = perfil;
    }
    public Character getEstado() {
        return this.estado;
    }
    
    public void setEstado(Character estado) {
        this.estado = estado;
    }




}


